### ISSUE TITLE
Error polling devices

### ISSUE THREAD

**Issue by rnilssoncx** [NorthernMan54/homebridge-tcc#105] opened 2021-05-28 18:31 UTC
I've been getting errors that the service isn't available - has anything changed?

```
[5/28/2021, 13:28:24] [Thermostat] pollDevices <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>

```

**Comment by NorthernMan54** [comment] 2022-02-10 00:09
Duplicate of #109

**Closed by NorthernMan54** 2022-02-10 00:09 UTC
