### ISSUE TITLE
ChangeThermostat Error: Error: timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by jguyca** [NorthernMan54/homebridge-tcc#97] opened 2021-03-09 06:40 UTC
Started getting this issue a few days ago while trying to update the temp on my thermostat.

When I restart homebridge, I can see the thermostat in apple home (pulls status ok), however as soon as I try to modify the temperature, I get the error below, and then the thermostat shows as "not responding" in apple home.

Really appreciate all the work you have done on this plugin, and for your help to look in to this issue.

Thank you!

[3/8/2021, 10:32:27 PM] [Thermostat] Setting target temperature for THERMOSTAT to 16.700000000000003°
ChangeThermostat Error: Error: timeout of 10000ms exceeded
    at createError (/homebridge/node_modules/homebridge-tcc/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/homebridge/node_modules/homebridge-tcc/node_modules/axios/lib/adapters/http.js:280:16)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tcc/node_modules/follow-redirects/index.js:165:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  config: {
    url: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><GetThermostat><sessionID>——————</sessionID><thermostatID>————</thermostatID></GetThermostat></soap:Body></soap:Envelope>',
    headers: {
      Accept: '*/*',
      'Content-Type': 'text/xml;charset=UTF-8',
      'user-agent': 'TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0',
      ADRUM: 'isAjax:true',
      'Accept-Language': 'en-ca',
      'Accept-Encoding': 'gzip, deflate, br',
      ADRUM_1: 'isMobile:true',
      soapAction: 'http://services.alarmnet.com/Services/MobileV2/GetThermostat',
      'Content-Length': 428
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/ws/MobileV2.asmx',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'tccna.honeywell.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/ws/MobileV2.asmx'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 428,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /ws/MobileV2.asmx HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: text/xml;charset=UTF-8\r\n' +
        'user-agent: TCCStageC/1092 CFNetwork/1125.2 Darwin/19.4.0\r\n' +
        'ADRUM: isAjax:true\r\n' +
        'Accept-Language: en-ca\r\n' +
        'Accept-Encoding: gzip, deflate, br\r\n' +
        'ADRUM_1: isMobile:true\r\n' +
        'soapAction: http://services.alarmnet.com/Services/MobileV2/GetThermostat\r\n' +
        'Content-Length: 428\r\n' +
        'Host: tccna.honeywell.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ws/MobileV2.asmx',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'tccna.honeywell.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://tccna.honeywell.com/ws/MobileV2.asmx',
    _timeout: Timeout {
      _idleTimeout: 10000,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 86084,
      _onTimeout: [Function (anonymous)],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 4246,
      [Symbol(triggerId)]: 4243
    },
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by jguyca** [comment] 2021-03-09 06:41
I removed my credentials from the log snippet above.

**Comment by NorthernMan54** [comment] 2021-03-09 13:54
Duplicate of #90

**Closed by NorthernMan54** 2021-03-09 13:54 UTC
