### ISSUE TITLE
Thermostat disappears on reboot of homebridge. It sometimes takes a second reboot for it to appear again.

### ISSUE THREAD

**Issue by jondthompson** [NorthernMan54/homebridge-tcc#57] opened 2020-04-29 20:11 UTC
When it comes back, it's always in the default room and loses the icon positioning data I've done in the room it belongs.

**Comment by NorthernMan54** [comment] 2020-05-02 13:44
Am thinking that this is caused by the TCC website not being available at the same time homebridge is rebooting.

The plugin grabs configuration details from the TCC website on startup and if it can't connect it doesn't know what to publish to HomeKit.

How often are you restarting homebridge?

**Comment by jondthompson** [comment] 2020-05-06 22:23
When there are updates to homebridge and/or plugins.  Could you cache the settings that it had previously and send them so that my icons stay in the same place?

**Comment by NorthernMan54** [comment] 2020-05-07 14:23
Unfortunatley those settings are not shared with Homebridge, but are part of the Home app.

I'm going to leave this as open issue so others are aware of this known issue, but at this time their is no resolution for the issue.

**Comment by jondthompson** [comment] 2020-05-07 16:14
Yes, the icon locations are part of the home app. However, the disappearing
and reappearing is your responsibility and should be fixed so it's stable.
Jon Thompson
Evolve
515 360 1351
www.dmevolve.com

**Comment by NorthernMan54** [comment] 2020-05-24 14:03
Fix for this is included in #59 

Closing this and will track via that issue

**Closed by NorthernMan54** 2020-05-24 14:03 UTC
