### ISSUE TITLE
Thermostat] pollDevices Error: TooManyAttempt

### ISSUE THREAD

**Issue by Tesla-P100FX** [NorthernMan54/homebridge-tcc#107] opened 2021-06-25 13:34 UTC
Using on Hoobs 3.3.5 and Node 14.15.1 Raspbien 10 TCC 0.2.23 Config is:

{
            "platform": "tcc",
            "plugin_map": {
                "plugin_name": "homebridge-tcc"
            },
            "name": "Thermostat",
            "refresh": 1200,
            "storage": "fs",
            "username": "xxxx",
            "password": "xxxx"
        }

Honeywell thermostat is a THM5320R

Most of the time works fine and once in a while shows unavailable in homekit with "Thermostat] pollDevices Error: TooManyAttempt"   Just changed poll to 1200 to see if that helps prevent error

**Comment by NorthernMan54** [comment] 2022-02-10 00:09
Duplicate of #109

**Closed by NorthernMan54** 2022-02-10 00:09 UTC
