### ISSUE TITLE
Homebridge 2.0 Readiness?

### ISSUE THREAD

**Issue by agilisone** [NorthernMan54/homebridge-tcc#151] opened 2024-12-07 07:06 UTC
### Current Situation

Is the plugin ready to support Homebridge V2?

### Proposed Change

As I understand it, Homebridge V2.0 will break some plugins that make use of old functions.

**Comment by lotz** [comment] 2024-12-12 14:02
This is a dupe of https://github.com/NorthernMan54/homebridge-tcc/issues/147. More discussion in that issue.

**Closed** 2024-12-13 13:58 UTC
Labels: enhancement
