### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by fleiscpj** [NorthernMan54/homebridge-tcc#133] opened 2023-04-03 00:59 UTC
Using Synology Homebridge install.  Not the docker implementation.  The following output occurred:

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save homebridge-tcc@0.2.34

[##################] | reify:moment: timing reifyNode:node_modules/homebridge-tcc/node
> node-expat@2.4.0 install
> node-gyp rebuild

gyp ERR! build error \ reify:googleapis: timing reifyNode:node_modules/homebridge-tcc/
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-tcc/node_modules/node-expat
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

**Comment by RichSimon** [comment] 2023-04-30 10:46
Having the same issue. Tried to update node 16, 17 (updated fine). Not allowed to update to node 18.

**Comment by tc8** [comment] 2023-05-11 08:04
I'm having the same issue.

**Comment by NorthernMan54** [comment] 2023-05-23 23:21
The install process uses node-gyp, which requires additional packages to be installed.  https://github.com/nodejs/node-gyp#on-unix.  Most of the homebridge images include the tools, but am thinking your Synology does not include it.

**Comment by NorthernMan54** [comment] 2023-05-30 00:03
duplicate of #134

**Closed by NorthernMan54** 2023-05-30 00:03 UTC
